### ISSUE TITLE
Error when first running `eyebrowse-restore-mode`

### ISSUE THREAD

**Issue by mrcnski** [FrostyX/eyebrowse-restore#2]
```
Error running timer ‘eyebrowse-restore-save-all’: (file-missing "Opening output file" "No such file or directory" "/Users/marcin/.emacs.d/eyebrowse-restore/Emacs - /Users/marcin/iCloud/org/work.org - [0 1:org 3] - 0")
```

(My frame title is `Emacs - /Users/marcin/iCloud/org/work.org - [0 1:org 3] - 0`).

**Comment by FrostyX** [comment]
Thank you for the report @m-cat.

This is probably caused by the filepath in your frame name. Eyebrowse-restore is creating backup files like this, `~/.emacs.d/eyebrowse-restore/someframename`, which in your case would be 

`~/.emacs.d/eyebrowse-restore/Emacs - /Users/marcin/iCloud/org/work.org - [0 1:org 3] - 0`

which points to a much deeper directory structure.

This one should be easy to fix, we somehow need to escape the `/` characters in the backup name. I think we can simply replace them with another character, maybe `#`?

**Comment by mrcnski** [comment]
I wonder if you could escape it like a URL, and then unescape before displaying it back to the user.

https://stackoverflow.com/a/9847319/6085242

**Comment by FrostyX** [comment]
> I wonder if you could escape it like a URL, and then unescape before displaying it back to the user.

Good idea, I implemented it. 
Please try if it works for you now :-)

**Comment by mrcnski** [comment]
Thank you, it works! 🙏
